/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppLibraryRouteRouteImport } from './routes/app/library/route'
import { Route as AppPlaylistRatingKeyRouteImport } from './routes/app/playlist.$ratingKey'
import { Route as AppLibraryTracksRouteImport } from './routes/app/library/tracks'
import { Route as AppLibraryPlaylistsRouteImport } from './routes/app/library/playlists'
import { Route as AppLibraryArtistsRouteImport } from './routes/app/library/artists'
import { Route as AppLibraryAlbumsRouteImport } from './routes/app/library/albums'
import { Route as AppArtistRatingKeyRouteImport } from './routes/app/artist.$ratingKey'
import { Route as AppAlbumRatingKeyRouteImport } from './routes/app/album.$ratingKey'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryRouteRoute = AppLibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaylistRatingKeyRoute = AppPlaylistRatingKeyRouteImport.update({
  id: '/playlist/$ratingKey',
  path: '/playlist/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryTracksRoute = AppLibraryTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppLibraryPlaylistsRoute = AppLibraryPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppLibraryArtistsRoute = AppLibraryArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppLibraryAlbumsRoute = AppLibraryAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppLibraryRouteRoute,
} as any)
const AppArtistRatingKeyRoute = AppArtistRatingKeyRouteImport.update({
  id: '/artist/$ratingKey',
  path: '/artist/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumRatingKeyRoute = AppAlbumRatingKeyRouteImport.update({
  id: '/album/$ratingKey',
  path: '/album/$ratingKey',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/library': typeof AppLibraryRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/library/albums': typeof AppLibraryAlbumsRoute
  '/app/library/artists': typeof AppLibraryArtistsRoute
  '/app/library/playlists': typeof AppLibraryPlaylistsRoute
  '/app/library/tracks': typeof AppLibraryTracksRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/library': typeof AppLibraryRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/library/albums': typeof AppLibraryAlbumsRoute
  '/app/library/artists': typeof AppLibraryArtistsRoute
  '/app/library/playlists': typeof AppLibraryPlaylistsRoute
  '/app/library/tracks': typeof AppLibraryTracksRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/app/library': typeof AppLibraryRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/album/$ratingKey': typeof AppAlbumRatingKeyRoute
  '/app/artist/$ratingKey': typeof AppArtistRatingKeyRoute
  '/app/library/albums': typeof AppLibraryAlbumsRoute
  '/app/library/artists': typeof AppLibraryArtistsRoute
  '/app/library/playlists': typeof AppLibraryPlaylistsRoute
  '/app/library/tracks': typeof AppLibraryTracksRoute
  '/app/playlist/$ratingKey': typeof AppPlaylistRatingKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/library'
    | '/app/settings'
    | '/app/'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/playlists'
    | '/app/library/tracks'
    | '/app/playlist/$ratingKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/app/library'
    | '/app/settings'
    | '/app'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/playlists'
    | '/app/library/tracks'
    | '/app/playlist/$ratingKey'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/setup'
    | '/app/library'
    | '/app/settings'
    | '/app/'
    | '/app/album/$ratingKey'
    | '/app/artist/$ratingKey'
    | '/app/library/albums'
    | '/app/library/artists'
    | '/app/library/playlists'
    | '/app/library/tracks'
    | '/app/playlist/$ratingKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playlist/$ratingKey': {
      id: '/app/playlist/$ratingKey'
      path: '/playlist/$ratingKey'
      fullPath: '/app/playlist/$ratingKey'
      preLoaderRoute: typeof AppPlaylistRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library/tracks': {
      id: '/app/library/tracks'
      path: '/tracks'
      fullPath: '/app/library/tracks'
      preLoaderRoute: typeof AppLibraryTracksRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/app/library/playlists': {
      id: '/app/library/playlists'
      path: '/playlists'
      fullPath: '/app/library/playlists'
      preLoaderRoute: typeof AppLibraryPlaylistsRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/app/library/artists': {
      id: '/app/library/artists'
      path: '/artists'
      fullPath: '/app/library/artists'
      preLoaderRoute: typeof AppLibraryArtistsRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/app/library/albums': {
      id: '/app/library/albums'
      path: '/albums'
      fullPath: '/app/library/albums'
      preLoaderRoute: typeof AppLibraryAlbumsRouteImport
      parentRoute: typeof AppLibraryRouteRoute
    }
    '/app/artist/$ratingKey': {
      id: '/app/artist/$ratingKey'
      path: '/artist/$ratingKey'
      fullPath: '/app/artist/$ratingKey'
      preLoaderRoute: typeof AppArtistRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/album/$ratingKey': {
      id: '/app/album/$ratingKey'
      path: '/album/$ratingKey'
      fullPath: '/app/album/$ratingKey'
      preLoaderRoute: typeof AppAlbumRatingKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppLibraryRouteRouteChildren {
  AppLibraryAlbumsRoute: typeof AppLibraryAlbumsRoute
  AppLibraryArtistsRoute: typeof AppLibraryArtistsRoute
  AppLibraryPlaylistsRoute: typeof AppLibraryPlaylistsRoute
  AppLibraryTracksRoute: typeof AppLibraryTracksRoute
}

const AppLibraryRouteRouteChildren: AppLibraryRouteRouteChildren = {
  AppLibraryAlbumsRoute: AppLibraryAlbumsRoute,
  AppLibraryArtistsRoute: AppLibraryArtistsRoute,
  AppLibraryPlaylistsRoute: AppLibraryPlaylistsRoute,
  AppLibraryTracksRoute: AppLibraryTracksRoute,
}

const AppLibraryRouteRouteWithChildren = AppLibraryRouteRoute._addFileChildren(
  AppLibraryRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppLibraryRouteRoute: typeof AppLibraryRouteRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumRatingKeyRoute: typeof AppAlbumRatingKeyRoute
  AppArtistRatingKeyRoute: typeof AppArtistRatingKeyRoute
  AppPlaylistRatingKeyRoute: typeof AppPlaylistRatingKeyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppLibraryRouteRoute: AppLibraryRouteRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumRatingKeyRoute: AppAlbumRatingKeyRoute,
  AppArtistRatingKeyRoute: AppArtistRatingKeyRoute,
  AppPlaylistRatingKeyRoute: AppPlaylistRatingKeyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
